name: Unit tests Zig

on:
  push:
    branches:
    - develop
    - master
    - zig-pkg
  pull_request:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      
      - name: Build Summary
        run: zig build -DTests -fsummary -freference-trace