name: Unit tests Zig (msvc)

on:
  push:
    branches:
    - develop
    - master
    - zig-pkg
  pull_request:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-windows-msvc, x86-windows-msvc, aarch64-windows-msvc]
    runs-on: windows-latest   
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.target == 'x86_64-windows-msvc' }}
        with:
          arch: amd64
      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.target == 'aarch64-windows-msvc' }}
        with:
          arch: amd64_arm64
      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.target == 'x86-windows-msvc' }}
        with:
          arch: amd64_x86
      
      # wait: https://github.com/ziglang/zig/issues/15448
      # - name: Build Summary
      #   run: zig build -DTests -fsummary -freference-trace -Dtarget=${{matrix.target}}
